name: LowCoreQuests
main: dev.jalikdev.lowCoreQuests.LowCoreQuests
version: 0.3.0
api-version: 1.21
depend: [LowCore]

commands:
  quests:
    description: Open quest menu
    usage: /quests
    aliases: [quest]
